日本語翻訳：Introduction, HTML
GameWith/Front-End-Performance-Checklist pull request #1
Opened 2020-02-14 17:22 UTC by nouvelle

**Fixes**: #

🚨 Please review the [guidelines for contributing](CONTRIBUTING.md) and our [code of conduct](../CODE_OF_CONDUCT.md) to this repository. 🚨
**Please complete these steps and check these boxes (by putting an x inside the brackets) before filing your PR:**

- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

#### Short description of what this resolves:
日本語への翻訳を行いました。

#### Proposed changes:

- Introduction
- HTML

👍 Thank you!

2020-02-15 03:45 UTC, noguchi-hiroshi commented on README.md
> +* ![Low][low] は、優先順位が **低い** ことを意味しています。
爆速で翻訳していただきありがとうございます 👍 

`低い`, `中程度`, `高い` の場合表記揺れが、気になるかな？と思いましたので、以下の様に統一するのはいかがでしょうか？

```
優先度が **低** であることを意味しています。
優先度が **中** であることを意味しています。
優先度が **高** であることを意味しています。
```

2020-02-15 05:57 UTC, nouvelle commented on README.md
> +* ![Low][low] は、優先順位が **低い** ことを意味しています。
レビューありがとうございます！
そうですね、そのように修正します👍

2020-02-17 07:20 UTC, inosy22 commented
@nouvelle 素早く翻訳していただき、ありがとうございます！

細かいですが、こちらのissueでお話のあった翻訳スタイルの内容について、修正依頼になります。
https://github.com/thedaviddias/Front-End-Performance-Checklist/issues/100

### 1. アルファベットの両端にスペースを入れる (状況によって)

参考: [Vue.js 公式サイト日本語翻訳ガイド](https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md#%E7%BF%BB%E8%A8%B3%E3%81%AE%E3%82%86%E3%82%89%E3%81%8E--%E3%83%88%E3%83%BC%E3%83%B3)
  
> 半角スペースでアルファベット両端を入れて読みやすく！
> > Vue.js is a library for building modern web interfaces.
>
> NG : Vue.jsはモダンなWebインターフェースを構築するためのライブラリです。
> OK : Vue.js はモダンな Web インターフェースを構築するためのライブラリです。
> 例外として、句読点の前後にアルファベットがある場合は、スペースを入れなくてもいいです。
>
> 読点: 技術的に、Vue.js は MVVM パターンの ViewModel レイヤに注目しています。

### 2. カッコは日本語にする場合に全角にする

参考: [JTF日本語標準スタイルガイド](https://www.jtf.jp/jp/style_guide/pdf/jtf_style_guide.pdf)

![スクリーンショット 2020-02-17 16 14 33](https://user-images.githubusercontent.com/10849664/74631576-9e428c00-51a0-11ea-808f-ff3cc6ac1916.png)

お手数ですが、翻訳スタイル統一のため、ご協力よろしくお願いいたします。

2020-02-17 12:59 UTC, nouvelle commented
> @nouvelle 素早く翻訳していただき、ありがとうございます！
> 
> 細かいですが、こちらのissueでお話のあった翻訳スタイルの内容について、修正依頼になります。
> [thedaviddias#100](https://github.com/thedaviddias/Front-End-Performance-Checklist/issues/100)
> 
> ### 1. アルファベットの両端にスペースを入れる (状況によって)
> 参考: [Vue.js 公式サイト日本語翻訳ガイド](https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md#%E7%BF%BB%E8%A8%B3%E3%81%AE%E3%82%86%E3%82%89%E3%81%8E--%E3%83%88%E3%83%BC%E3%83%B3)
> 
> > 半角スペースでアルファベット両端を入れて読みやすく！
> > > Vue.js is a library for building modern web interfaces.
> > 
> > 
> > NG : Vue.jsはモダンなWebインターフェースを構築するためのライブラリです。
> > OK : Vue.js はモダンな Web インターフェースを構築するためのライブラリです。
> > 例外として、句読点の前後にアルファベットがある場合は、スペースを入れなくてもいいです。
> > 読点: 技術的に、Vue.js は MVVM パターンの ViewModel レイヤに注目しています。
> 
> ### 2. カッコは日本語にする場合に全角にする
> 参考: [JTF日本語標準スタイルガイド](https://www.jtf.jp/jp/style_guide/pdf/jtf_style_guide.pdf)
> 
> ![スクリーンショット 2020-02-17 16 14 33](https://user-images.githubusercontent.com/10849664/74631576-9e428c00-51a0-11ea-808f-ff3cc6ac1916.png)
> 
> お手数ですが、翻訳スタイル統一のため、ご協力よろしくお願いいたします。

細かい部分まで見ていただきありがとうございます！
修正いたしましたのでご確認頂けると幸いです！

2020-02-20 07:07 UTC, inosy22 requested changes
@nouvelle ご返信遅くなり申し訳ありません！

スタイル修正ありがとうございます！
細かい話ではありますが、スタイル等についていくつか気になった箇所のコメントをしたので、問題なければご対応いただけると助かります。
(私が間違ってる等もありえますので、気軽にご返答いただければと思います)

お手数おかけしますが、ご確認よろしくお願いいたします。

2020-02-20 07:07 UTC, inosy22 commented on README.md
> +<p align="center">シンプルなルール: "パフォーマンスを考慮してデザイン • コーディングすること"</p>
`デザイン • コーディング` の 「•」を全角にし、前後の半角スペースはないと良さそうです

2020-02-20 07:07 UTC, inosy22 commented on README.md
> +パフォーマンスは大きなテーマですが、いつも "バックエンド" や "管理者" の問題というわけではありません。フロントエンドの責任範囲でもあります。このフロントエンドパフォーマンスチェックリストは、フロントエンド開発者としてプロジェクト(個人 or 業務)に充たる場合に、確認もしくは気にしておくべき項目を網羅的にリストアップしたものです。
`個人 or 業務` 原文だと、and なので、個人でも業務でも当てはまるという意味のようになるのでしょうか？

2020-02-20 07:07 UTC, inosy22 commented on README.md
> +- [ ] **HTML の軽量化 (Minified):** ![medium] HTML コードは圧縮され、コメント、空白、改行が本番のファイルから削除されていること。
`軽量化 (Minified)` こちらは、全角カッコにするかつ半角スペースがない方が良いと思われます

2020-02-20 07:07 UTC, inosy22 commented on README.md
> +    *理由 :*
これ系を全体で統一したいのですが、
`理由` と `:` の間に半角スペースなしで統一したいと考えています。
`:` は、Vue.js のルールに基づき、原文引用で半角統一で問題ないです。

2020-02-20 07:07 UTC, inosy22 commented on README.md
> +- [ ] **prefetch 、dns-prefetch 、prerende での事前読み込みによる最適化:** ![low] 一般的なブラウザでは、`<link>`タグに "rel" 属性のディレクティブ指定することで特定の URL を事前読み込みすることができます。
- `prefetch 、dns-prefetch 、prerende` : Vue.js のスタイルだと、記号の前後は半角スペースなしとなっているので、ない方が良いかと思います
- `prerende` : `prerender` のタイポかと思われます

2020-02-20 07:07 UTC, inosy22 commented on README.md
> +    > 事前読込み (Prefetching) により、ブラウザはユーザが近い将来アクセスする可能性のあるコンテンツの表示に必要なリソースを事前に取得しておくことができます。ブラウザはこれらのリソースをキャッシュに保存するので、コンテンツが異なるドメインを使っている場合でも Web ページの読み込みを高速化できます。 Web ページの読み込みが完了し、アイドル時間が経過すると、ブラウザは他の
- ` (Prefetching) ` : 全角カッコ かつ スペースなしが理想です
- `(事前読み込み済み)` : 全角カッコにしていただけるといいです

2020-02-20 13:09 UTC, nouvelle commented on README.md
> +パフォーマンスは大きなテーマですが、いつも "バックエンド" や "管理者" の問題というわけではありません。フロントエンドの責任範囲でもあります。このフロントエンドパフォーマンスチェックリストは、フロントエンド開発者としてプロジェクト(個人 or 業務)に充たる場合に、確認もしくは気にしておくべき項目を網羅的にリストアップしたものです。
確かに、おっしゃる通りですね。
**（個人でも業務でも）** という書き方にしますね。
ご指摘ありがとうございます！

2020-02-20 13:22 UTC, nouvelle commented
細かくチェックしていただき本当にありがとうございます！
私の方でも今一度全体の確認を行いましたが、再度ご確認頂けると幸いです。
よろしくお願い致します。

2020-02-21 03:56 UTC, inosy22 approved these changes
@nouvelle 
ご対応いただきありがとうございました！
とても良さそうに見えます！

マージなどの方法については、
@53able から後ほどご連絡がくると思うので少しお待ちください！

2020-02-21 04:41 UTC, 53able commented on README.md
> +    > コメントはユーザにとって何も役に立たないので、本番のファイルからは削除すべきです。コメントを保持したくなるケースは、ライブラリのソースを保持する必要がある場合くらいです。(keep the origin for a library)
`(keep the origin for a library)` は、消し忘れでしょうか?

2020-02-21 04:54 UTC, nouvelle commented on README.md
> +    > コメントはユーザにとって何も役に立たないので、本番のファイルからは削除すべきです。コメントを保持したくなるケースは、ライブラリのソースを保持する必要がある場合くらいです。(keep the origin for a library)
この部分は意訳している部分もあったので、原文があった方がいいかなとも思ったのですが、なくてもわかるようでしたら削除します。
いかがでしょうか？？

2020-02-21 05:00 UTC, 53able commented on README.md
> +    > コメントはユーザにとって何も役に立たないので、本番のファイルからは削除すべきです。コメントを保持したくなるケースは、ライブラリのソースを保持する必要がある場合くらいです。(keep the origin for a library)
原文の意図が日本語で通じれば、原文は不要だと思います🙏
@nouvelle

2020-02-21 05:29 UTC, nouvelle commented on README.md
> +    > コメントはユーザにとって何も役に立たないので、本番のファイルからは削除すべきです。コメントを保持したくなるケースは、ライブラリのソースを保持する必要がある場合くらいです。(keep the origin for a library)
@53able 
了解です。
いろいろとアドバイスありがとうございます ！

2020-02-21 05:42 UTC, 53able approved these changes
LGTMです👍👍
お疲れさまでした✨
マージお願いします!
@nouvelle

2020-02-21 06:02 UTC, merged