[WIP] Translate server section to Japanese
GameWith/Front-End-Performance-Checklist pull request #2
Opened 2020-02-16 18:40 UTC by inosy22

**Fixes**: #

🚨 Please review the [guidelines for contributing](CONTRIBUTING.md) and our [code of conduct](../CODE_OF_CONDUCT.md) to this repository. 🚨
**Please complete these steps and check these boxes (by putting an x inside the brackets) before filing your PR:**

- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.

#### Short description of what this resolves:

#### Proposed changes:

-
-
-

👍 Thank you!

2020-02-21 07:09 UTC, nouvelle commented
@inosy22 

細かいですが、翻訳スタイルの内容について気になった点がありました。

- サーバー　→　サーバ
- ユーザー　→　ユーザ

ご確認の上、修正をお願いできますでしょうか。

1. 長音訳のついて
参考: [Vue.js 公式サイト日本語翻訳ガイド](https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md#%E9%95%B7%E9%9F%B3%E8%A8%B3%E3%81%AE%E3%81%A4%E3%81%84%E3%81%A6)

> 
> 原則、長音なしで翻訳する。
> 
> NG: コンピューター
> OK: コンピュータ
> ただし、長音なしで訳した場合、意味が分かりにくいものは、例外として長音ありで訳してもよいです。
> 
> > Pull Request flow
> 
> NG: プルリクエストフロ
> OK: プルリクエストフロー
> 長音訳例外リスト
> > NOTE: 以下のリストは随時追加していく
> 
> error: エラー
> throw: スロー
> flow: フロー
> ...

よろしくお願い致します！

2020-02-26 10:43 UTC, inosy22 commented
@nouvelle レビューありがとうございます！
対応遅くなり申し訳ありません 🙇 

 - ヘッダー -> ヘッダ
 - ユーザー -> ユーザ
 - サーバー -> サーバ

を対応いたしました！

上記対応済みのものは、伸ばし棒なしで通じる単語として一般に普及しているをGoogle検索で確認しているのですが、
下の単語については、伸ばし棒があるものが一般的なようなのでそのままにしています！

 - クッキー
 - サービスワーカ

2020-02-26 12:50 UTC, nouvelle requested changes
伸ばし棒の翻訳スタイル修正はOKだと思います。
ただ、１箇所変換ミスと思われる部分がありましたので、ご確認お願いします。

2020-02-26 12:50 UTC, nouvelle commented on README.md
> +    > クッキーは、ウェブサーバとブラウザ間で HTTP ヘッダでやりとりされます。ユーザの応答時間への家今日を最小限に抑えるために、クッキーのサイズをできる限り小さくすることが重要です。
> ユーザの応答時間への家今日を

ユーザの応答時間への**影響**を
でしょうか？

2020-02-27 11:19 UTC, inosy22 commented on README.md
> +    > クッキーは、ウェブサーバとブラウザ間で HTTP ヘッダでやりとりされます。ユーザの応答時間への家今日を最小限に抑えるために、クッキーのサイズをできる限り小さくすることが重要です。
見つけていただきありがとうございます＠
間違意を修正しました！

2020-02-27 11:20 UTC, inosy22 commented
@53able 全体的に終わったので見ていただけると助かります！

2020-02-27 12:30 UTC, nouvelle commented on README.md
> +    > クッキーは、ウェブサーバとブラウザ間で HTTP ヘッダでやりとりされます。ユーザの応答時間への家今日を最小限に抑えるために、クッキーのサイズをできる限り小さくすることが重要です。
修正ありがとうございます！

2020-02-29 04:29 UTC, 53able commented
@inosy22 全て ですます 調に統一しましょう

2020-02-29 06:40 UTC, 53able reviewed
@inosy22 詳細までレビューをしてみました。
提案に同意の判断をしましたら、修正お願いします。

2020-02-29 06:40 UTC, 53able commented on README.md
> +- [ ] **GZIP / Brotli 圧縮が有効になっている:** ![high] GZIP や Brotli などの圧縮方法を利用して、 JavaScript ファイルのサイズを小さくします。ファイルのサイズを小さくすると、ユーザはアセットをより速くダウンロードできるようになり、パフォーマンスが向上します。
`圧縮が有効になっています`

2020-02-29 06:40 UTC, 53able commented on README.md
> +- [ ] **HTTP キャッシュヘッダを適切に設定する:** ![high] HTTP ヘッダを設定して、ブラウザとサーバ間の往復コストを回避します。
`設定します`

2020-02-29 06:40 UTC, 53able commented on README.md
> +- [ ] **到達可能なファイルを提供する:** ![high] 到達不能なファイルへのリクエストを避けます（404）。
`提供します`

2020-02-29 06:40 UTC, 53able commented on README.md
> +- [ ] **同じプロトコルからファイルを提供する:** ![high] 例えば、 HTTPS を使用している Web サイトで、 HTTP を使用したソースからファイルを提供する Web サイトを作成しないでください。 Web サイトが HTTPS を使用している場合、外部ファイルは同じプロトコルから取得する必要があります。
`同じプロトコルからファイルを提供します`

2020-02-29 06:40 UTC, 53able commented on README.md
> +- [ ] **CDN を使用してアセットを配信する:** ![medium] CDN を利用して、コンテンツをより速く世界中に配信します。
`アセットを配信します`

2020-02-29 06:40 UTC, 53able commented on README.md
> +    > 不要なクッキーを排除する。
`不要なクッキーを排除します。`

2020-02-29 06:40 UTC, 53able commented on README.md
> +* [ ] **クッキーサイズ:** ![medium] クッキーを利用しているのであれば、各クッキーが4096バイトを超えないようにし、ドメイン毎に20を超えるクッキーがないようにしてください。
漢字を使うことを提案します。

`クッキーが無いようにしてください`

2020-02-29 06:40 UTC, 53able commented on README.md
> +    > 500 KB 未満を目標にするのが理想ですが、 Web の状態では、KB の中央値が約 1500 KB （モバイルでも）であることが示されています。ターゲットユーザ、ネットワーク接続、デバイスに応じて、可能な限り総キロバイト数を減らすことで、可能な限り最高のユーザ体験を提供することができます。
` the median of Kilobytes is around 1500 KB` はページ容量のことを指しているので、
`ページ容量の中央値が約 1500 KB` と表したほうが適切だと提案します。

2020-02-29 06:40 UTC, 53able commented on README.md
> +    > Web サイトやアプリが高速であればあるほど、直帰が増加する可能性を減らし、ユーザや将来のクライアントを失う可能性を減らします。主題に関する十分な調査は、この点を証明します。
`bounce` は、アクセス解析の用語で `直帰` は間違ってないですね。
より分かりやすいく、`離脱` と表現することを提案します。

2020-02-29 06:40 UTC, 53able commented on README.md
> +- [ ] **Web サイトが HTTPS を使用している:** ![high]
`ウェブサイトが HTTPS を使用しています`

2020-02-29 06:40 UTC, 53able commented on README.md
> +    > Web サイトやアプリが高速であればあるほど、直帰が増加する可能性を減らし、ユーザや将来のクライアントを失う可能性を減らします。主題に関する十分な調査は、この点を証明します。
`website` は、 `ウェブサイト` にしましょうか。

2020-02-29 06:40 UTC, 53able commented on README.md
> +    > HTTPS は、 e コマース Web サイトだけではなく、データをやりとりする全ての Web サイト用です。データとは、ユーザが共有するデータ、または外部エンティティと共有するデータです。今時の最新ブラウザは安全でないサイトの機能を制限しています。例えば、インスタンスが HTTPS を使用していない場合、位置情報、プッシュ通知、およびサービスワーカーは機能しません。また、今時は S
`websites ` ⇒ `ウェブサイト`

2020-02-29 06:40 UTC, 53able commented on README.md
> +- [ ] **HTTP リクエストの最小化:** ![high] リクエストされている全てのファイルが Web サイトまたはアプリケーションに不可欠であることを常に確認してください。
`websites ` ⇒ `ウェブサイト`

2020-02-29 06:40 UTC, 53able commented on README.md
> +- [ ] **同じプロトコルからファイルを提供する:** ![high] 例えば、 HTTPS を使用している Web サイトで、 HTTP を使用したソースからファイルを提供する Web サイトを作成しないでください。 Web サイトが HTTPS を使用している場合、外部ファイルは同じプロトコルから取得する必要があります。
`websites ` ⇒ `ウェブサイト`

2020-02-29 06:40 UTC, 53able commented on README.md
> +    > HTTPS は、 e コマース Web サイトだけではなく、データをやりとりする全ての Web サイト用です。データとは、ユーザが共有するデータ、または外部エンティティと共有するデータです。今時の最新ブラウザは安全でないサイトの機能を制限しています。例えば、インスタンスが HTTPS を使用していない場合、位置情報、プッシュ通知、およびサービスワーカーは機能しません。また、今時は S
`today` は、`今時` だと、くだけた感がありますので、 もう少し堅くして、 `現在` または `現代` とする提案をします。

2020-03-04 08:02 UTC, inosy22 commented
@53able 指摘事項修正しました！
https://github.com/GameWith/Front-End-Performance-Checklist/pull/2/commits/36225a4ccb86046f32dff1d2f558b5b5b8737581

 - ですます調に統一
    - 対象がチェックリストの項目なので、他部分と合わせて名詞化した方が自然だと感じたので、名詞化しました！
 - web サイト -> ウェブサイト
 - 今時は -> 現在は

 加えて、自分で気になったところ見つけたので修正
`（そして無料の、 [Let's Encrypt](https://letsencrypt.org/) に感謝です。）`
↓
`（そして、 [Let's Encrypt](https://letsencrypt.org/) のおかげで無料です。）`

2020-03-12 12:38 UTC, 53able commented
@inosy22 チェックリスト項目は、名詞止め するのは同意します。
僕の翻訳も含め、全体で合わせていきましょう。
後ほど、全体を調整するPRが必要そうですね。

2020-03-12 12:45 UTC, 53able commented
`service workers` の翻訳ですが、 僕が担当している[JavaScriptでのコメント](https://github.com/GameWith/Front-End-Performance-Checklist/pull/5#discussion_r386272055) に書いたとおり、紹介されているGoogleの日本語ドキュメントに習い、*Service Worker*　とすることのを提案します。
@inosy22

2020-03-17 06:31 UTC, inosy22 commented
@53able 漏れていた部分等の修正を行いましたので、再度ご確認よろしくお願いいたします！

2020-03-17 12:02 UTC, 53able commented
@inosy22 多数の修正ありがとうございます
https://github.com/GameWith/Front-End-Performance-Checklist/pull/2/files#r386000679
一点、こちら修正が済んだら、良さそうです😉  

2020-03-17 12:11 UTC, inosy22 commented
@53able おっとすいません！そちらも直しました！

2020-03-17 12:23 UTC, 53able approved these changes
👍マージお願いします！

2020-03-18 08:28 UTC, merged